# Generated by Django 6.0 on 2025-12-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpportunityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="opportunities.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="opportunities.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description_en", models.TextField(blank=True, default="")),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                ("is_remote", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="opportunities.domain",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="opportunities.location",
                    ),
                ),
                (
                    "op_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="opportunities.opportunitytype",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="opportunities.specialization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["parent", "name"], name="opportuniti_parent__3d842b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("parent", "name")},
        ),
        migrations.AddIndex(
            model_name="specialization",
            index=models.Index(
                fields=["domain", "name"], name="opportuniti_domain__c1cc26_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="specialization",
            unique_together={("domain", "name")},
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["op_type"], name="opportuniti_op_type_54a3d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["domain"], name="opportuniti_domain__fc59dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["specialization"], name="opportuniti_special_a9c4f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["location"], name="opportuniti_locatio_0f5448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["is_remote"], name="opportuniti_is_remo_7f34ea_idx"
            ),
        ),
    ]
