# Generated by Django 6.0 on 2025-12-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="opportunity_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domains",
                to="opportunities.opportunitytype",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _populate_domain_types(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="domain",
            name="opportunity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domains",
                to="opportunities.opportunitytype",
            ),
        ),
    ]


def _populate_domain_types(apps, schema_editor):
    OpportunityType = apps.get_model("opportunities", "OpportunityType")
    Domain = apps.get_model("opportunities", "Domain")

    # Default all existing domains to JOB unless already set.
    job_type, _ = OpportunityType.objects.get_or_create(name="JOB")
    Domain.objects.filter(opportunity_type__isnull=True).update(opportunity_type=job_type)
