# Generated by Django 6.0 on 2025-12-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0002_domain_opportunity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="opportunity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domains",
                to="opportunities.opportunitytype",
            ),
        ),
    ]
