# Generated by Django 6.0 on 2025-12-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0003_alter_domain_opportunity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                ("raw_text", models.TextField(blank=True, default="")),
                (
                    "detected_language",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("text_en", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("TRANSLATED", "Translated"),
                            ("EXTRACTED", "Extracted"),
                            ("FAILED", "Failed"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "published_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("TELEGRAM", "Telegram"),
                            ("RSS", "RSS"),
                            ("WEB", "Web"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("poll_interval_minutes", models.PositiveIntegerField(default=10)),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("CONTRACT", "Contract"),
                    ("INTERNSHIP", "Internship"),
                ],
                default="UNKNOWN",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("STUDENT", "Student"),
                    ("GRADUATE", "Graduate"),
                    ("JUNIOR", "Junior"),
                    ("MID", "Mid"),
                    ("SENIOR", "Senior"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="max_compensation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="min_compensation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="organization",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("REMOTE", "Remote"),
                    ("ONSITE", "Onsite"),
                    ("HYBRID", "Hybrid"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="raw",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_opportunity",
                to="opportunities.rawopportunity",
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["work_mode"], name="opportuniti_work_mo_135108_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["employment_type"], name="opportuniti_employm_be5b86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["experience_level"], name="opportuniti_experie_99b990_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(
                fields=["deadline"], name="opportuniti_deadlin_33576f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=models.Index(fields=["status"], name="opportuniti_status_6a1f9f_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["source_type", "enabled"], name="opportuniti_source__f672d3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="source",
            unique_together={("source_type", "name")},
        ),
        migrations.AddField(
            model_name="rawopportunity",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raw_items",
                to="opportunities.source",
            ),
        ),
        migrations.AddIndex(
            model_name="rawopportunity",
            index=models.Index(
                fields=["source", "external_id"], name="opportuniti_source__478f90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawopportunity",
            index=models.Index(fields=["status"], name="opportuniti_status_2c1fc5_idx"),
        ),
        migrations.AddConstraint(
            model_name="rawopportunity",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="uniq_raw_source_external_id"
            ),
        ),
    ]
