# Generated by Django 6.0 on 2025-12-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0004_rawopportunity_source_jobopportunity_deadline_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobOpportunity",
            new_name="Opportunity",
        ),
    ]


