# Generated by Django 6.0 on 2025-12-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0005_rename_jobopportunity_to_opportunity"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_op_type_2f58e5_idx",
            old_name="opportuniti_op_type_54a3d7_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_domain__2c0b1d_idx",
            old_name="opportuniti_domain__fc59dd_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_special_2b2c88_idx",
            old_name="opportuniti_special_a9c4f6_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_locatio_d53d73_idx",
            old_name="opportuniti_locatio_0f5448_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_is_remo_8809b4_idx",
            old_name="opportuniti_is_remo_7f34ea_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_work_mo_1b74b9_idx",
            old_name="opportuniti_work_mo_135108_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_employm_b10900_idx",
            old_name="opportuniti_employm_be5b86_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_experie_27cffe_idx",
            old_name="opportuniti_experie_99b990_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_deadlin_294f61_idx",
            old_name="opportuniti_deadlin_33576f_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="opportuniti_status_fb4df4_idx",
            old_name="opportuniti_status_6a1f9f_idx",
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="raw",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunity",
                to="opportunities.rawopportunity",
            ),
        ),
    ]
