# Generated by Django 6.0 on 2025-12-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "opportunities",
            "0006_rename_opportuniti_op_type_54a3d7_idx_opportuniti_op_type_2f58e5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rawopportunity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
