# Generated by Django 6.0 on 2025-12-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0007_rawopportunity_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawopportunity",
            name="content_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
