# Generated by Django 6.0 on 2025-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0008_rawopportunity_content_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawopportunity",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("TRANSLATED", "Translated"),
                    ("PROCESSING", "Processing"),
                    ("EXTRACTED", "Extracted"),
                    ("FAILED", "Failed"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
