# Generated by Django 6.0 on 2025-12-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0009_add_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="items_created_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="items_updated_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="last_error_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="last_error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="source",
            name="last_success_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="successful_runs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="total_runs",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
