# Generated by Django 6.0 on 2025-12-17 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold_score", models.FloatField(default=7.0)),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("INSTANT", "Instant"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                        ],
                        default="INSTANT",
                        max_length=10,
                    ),
                ),
                ("notify_via_telegram", models.BooleanField(default=True)),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("ANY", "Any"),
                            ("REMOTE", "Remote"),
                            ("ONSITE", "Onsite"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="ANY",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_domains",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_by_configs",
                        to="opportunities.domain",
                    ),
                ),
                (
                    "preferred_locations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_by_configs",
                        to="opportunities.location",
                    ),
                ),
                (
                    "preferred_opportunity_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_by_configs",
                        to="opportunities.opportunitytype",
                    ),
                ),
                (
                    "preferred_specializations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_by_configs",
                        to="opportunities.specialization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
