# Generated by Django 6.0 on 2025-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchconfig",
            name="deadline_after",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="deadline_before",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("ANY", "Any"),
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("CONTRACT", "Contract"),
                    ("INTERNSHIP", "Internship"),
                ],
                default="ANY",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("ANY", "Any"),
                    ("STUDENT", "Student"),
                    ("GRADUATE", "Graduate"),
                    ("JUNIOR", "Junior"),
                    ("MID", "Mid"),
                    ("SENIOR", "Senior"),
                ],
                default="ANY",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="max_compensation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="min_compensation",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
