# Generated by Django 6.0 on 2025-12-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0002_matchconfig_deadline_after_and_more"),
        ("opportunities", "0003_alter_domain_opportunity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchconfig",
            name="email_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTANT", "Instant"),
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="max_alerts_per_day",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="muted_opportunity_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="muted_by_configs",
                to="opportunities.opportunitytype",
            ),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="notify_via_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="notify_via_web_push",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="quiet_hours_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="quiet_hours_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="telegram_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTANT", "Instant"),
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matchconfig",
            name="web_push_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTANT", "Instant"),
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
