# Generated by Django 6.0 on 2025-12-30 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0009_add_processing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillGapAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="GENERATING",
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking async processing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "missing_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of skills the user is missing for this opportunity",
                    ),
                ),
                (
                    "skill_gaps",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed gap analysis with current vs required proficiency levels",
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recommended learning paths and actions to bridge gaps",
                    ),
                ),
                (
                    "alternative_suggestions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Alternative opportunities or career paths if gaps are too large",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence in the analysis (0-1)",
                        null=True,
                    ),
                ),
                (
                    "estimated_time_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated months to bridge major skill gaps",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if analysis failed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_gap_analyses",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_gap_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="skill_gap_a_user_id_62a4bf_idx"
                    ),
                    models.Index(
                        fields=["opportunity", "created_at"],
                        name="skill_gap_a_opportu_e6d41d_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="skill_gap_a_status_b8b681_idx",
                    ),
                ],
                "unique_together": {("user", "opportunity")},
            },
        ),
    ]
