# Generated by Django 6.0 on 2025-12-28 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAPICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("groq", "Groq"),
                            ("huggingface", "Hugging Face"),
                            ("stub", "Stub/Test"),
                        ],
                        help_text="AI provider used",
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model name/version used", max_length=100
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("text_generation", "Text Generation"),
                            ("json_generation", "JSON Generation"),
                            ("translation", "Translation"),
                            ("embedding", "Embedding"),
                        ],
                        help_text="Type of AI operation",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("extraction", "Data Extraction"),
                            ("matching", "User Matching"),
                            ("cover_letter", "Cover Letter Generation"),
                            ("cv_processing", "CV Processing"),
                            ("system", "System/Test"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Business context of the call",
                        max_length=20,
                    ),
                ),
                (
                    "prompt_length",
                    models.PositiveIntegerField(
                        help_text="Length of input prompt in characters"
                    ),
                ),
                (
                    "response_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Length of response in characters",
                        null=True,
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated tokens used (if provided by API)",
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the API call was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if the call failed"
                    ),
                ),
                (
                    "api_key_masked",
                    models.CharField(
                        blank=True,
                        help_text="Masked API key identifier for tracking",
                        max_length=50,
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        help_text="API call duration in milliseconds"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the call was made"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with the call (null for system calls)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "created_at"],
                        name="ai_usage_ai_provide_d2093c_idx",
                    ),
                    models.Index(
                        fields=["context", "created_at"],
                        name="ai_usage_ai_context_1a2566_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_usage_ai_user_id_392d91_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="ai_usage_ai_success_3b3181_idx",
                    ),
                ],
            },
        ),
    ]
