# Generated by Django 6.0 on 2025-12-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_usage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiapicall",
            name="api_key_identifier",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the specific API key used (e.g., key index or hash)",
                max_length=100,
            ),
        ),
    ]
