"""
Django settings for opportunity_finder project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from BASE_DIR/.env (not committed to git)
load_dotenv(BASE_DIR / ".env")


def env_bool(key: str, default: bool = False) -> bool:
    val = os.getenv(key)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def env_csv(key: str, default: list[str] | None = None) -> list[str]:
    val = os.getenv(key)
    if not val:
        return default or []
    return [item.strip() for item in val.split(",") if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-insecure-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env_csv("DJANGO_ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    # Local apps
    "accounts.apps.AccountsConfig",
    "profiles.apps.ProfilesConfig",
    "opportunities.apps.OpportunitiesConfig",
    "configs.apps.ConfigsConfig",
    "ingestion.apps.IngestionConfig",
    "ai.apps.AiConfig",
    "processing.apps.ProcessingConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "opportunity_finder.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "opportunity_finder.wsgi.application"

# Custom user model (email-based auth)
AUTH_USER_MODEL = "accounts.User"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def parse_database_url(database_url: str) -> dict:
    """
    Minimal DATABASE_URL parser for Postgres.

    Expected formats:
      - postgres://user:pass@host:5432/dbname
      - postgresql://user:pass@host/dbname
    """
    parsed = urlparse(database_url)
    scheme = (parsed.scheme or "").lower()
    if scheme not in {"postgres", "postgresql"}:
        raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme}")

    # urlparse may keep percent-encoding in username/password
    user = unquote(parsed.username or "")
    password = unquote(parsed.password or "")

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": (parsed.path or "").lstrip("/"),
        "USER": user,
        "PASSWORD": password,
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }


database_url = os.getenv("DATABASE_URL")
if database_url:
    DATABASES = {"default": parse_database_url(database_url)}
elif os.getenv("PGDATABASE") or os.getenv("POSTGRES_DB"):
    # Alternative explicit Postgres env vars (handy on some hosts)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("PGDATABASE") or os.getenv("POSTGRES_DB") or "",
            "USER": os.getenv("PGUSER") or os.getenv("POSTGRES_USER") or "",
            "PASSWORD": os.getenv("PGPASSWORD") or os.getenv("POSTGRES_PASSWORD") or "",
            "HOST": os.getenv("PGHOST") or os.getenv("POSTGRES_HOST") or "localhost",
            "PORT": os.getenv("PGPORT") or os.getenv("POSTGRES_PORT") or "5432",
        }
    }
else:
    # Safe local default
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# DRF / Auth
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Opportunity Finder API",
    "DESCRIPTION": "Backend API for Opportunity Finder (auth, opportunities, matching, notifications).",
    "VERSION": "0.1.0",
    # Swagger UI will use Bearer auth automatically when security schemes are present.
    "SERVE_INCLUDE_SCHEMA": False,
    # Important for file uploads: request schema differs from response schema (URL string vs binary upload).
    "COMPONENT_SPLIT_REQUEST": True,
}

# Telegram ingestion (Pyrogram)
PYROGRAM_API_ID = os.getenv("PYROGRAM_API_ID")
PYROGRAM_API_HASH = os.getenv("PYROGRAM_API_HASH")
PYROGRAM_SESSION_STRING = os.getenv("PYROGRAM_SESSION_STRING")

# AI (provider router)
AI_PROVIDER = os.getenv("AI_PROVIDER", "stub").strip().lower()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.0-flash").strip()
GEMINI_API_BASE = os.getenv("GEMINI_API_BASE", "https://generativelanguage.googleapis.com").strip().rstrip("/")
AI_TIMEOUT_SECONDS = float(os.getenv("AI_TIMEOUT_SECONDS", "60"))
AI_TEMPERATURE = float(os.getenv("AI_TEMPERATURE", "0.2"))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# Hugging Face (Inference API)
HF_API_TOKEN = os.getenv("HF_API_TOKEN")  # optional for some models, recommended
HF_MODEL = os.getenv("HF_MODEL", "google/gemma-2b-it").strip()
# Hugging Face deprecated api-inference host; router is the current endpoint.
# Base should be the router host. Endpoints vary by mode below.
HF_API_BASE = os.getenv("HF_API_BASE", "https://router.huggingface.co").strip().rstrip("/")
HF_MODE = os.getenv("HF_MODE", "openai").strip().lower()  # openai | classic
HF_MAX_NEW_TOKENS = int(os.getenv("HF_MAX_NEW_TOKENS", "256"))
HF_WAIT_FOR_MODEL = env_bool("HF_WAIT_FOR_MODEL", default=True)

# Celery (async tasks)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE", "UTC")

# Celery Beat (periodic scheduler)
# Runs every minute and enqueues per-Source ingestion tasks if due.
CELERY_BEAT_SCHEDULE = {
    "ingestion-ingest-due-sources-every-minute": {
        "task": "ingestion.tasks.ingest_due_sources",
        "schedule": 60.0,
        "args": (None, 50),  # source_type=None (all), limit=50
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media (uploads) - used for CV file reference storage in `profiles`
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
