"""
Django settings for opportunity_finder project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from kombu import Queue

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from BASE_DIR/.env (not committed to git)
load_dotenv(BASE_DIR / ".env")


def env_bool(key: str, default: bool = False) -> bool:
    val = os.getenv(key)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def env_csv(key: str, default: list[str] | None = None) -> list[str]:
    val = os.getenv(key)
    if not val:
        return default or []
    return [item.strip() for item in val.split(",") if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-insecure-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env_csv(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "192.168.146.17"]
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    # Local apps
    "opportunity_finder",
    "accounts.apps.AccountsConfig",
    "profiles.apps.ProfilesConfig",
    "opportunities.apps.OpportunitiesConfig",
    "configs.apps.ConfigsConfig",
    "ingestion.apps.IngestionConfig",
    "ai.apps.AiConfig",
    "processing.apps.ProcessingConfig",
    "matching.apps.MatchingConfig",
    "notifications.apps.NotificationsConfig",
    "resume_extractions.apps.ResumeExtractionsConfig",
    "cover_letters.apps.CoverLettersConfig",
    "ai_usage.apps.AiUsageConfig",
    "skill_gap_analysis.apps.SkillGapAnalysisConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "opportunity_finder.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "opportunity_finder.wsgi.application"

# Custom user model (email-based auth)
AUTH_USER_MODEL = "accounts.User"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def parse_database_url(database_url: str) -> dict:
    """
    Minimal DATABASE_URL parser for Postgres.

    Expected formats:
      - postgres://user:pass@host:5432/dbname
      - postgresql://user:pass@host/dbname
    """
    parsed = urlparse(database_url)
    scheme = (parsed.scheme or "").lower()
    if scheme not in {"postgres", "postgresql"}:
        raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme}")

    # urlparse may keep percent-encoding in username/password
    user = unquote(parsed.username or "")
    password = unquote(parsed.password or "")

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": (parsed.path or "").lstrip("/"),
        "USER": user,
        "PASSWORD": password,
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }


database_url = os.getenv("DATABASE_URL")
if database_url:
    DATABASES = {"default": parse_database_url(database_url)}
elif os.getenv("PGDATABASE") or os.getenv("POSTGRES_DB"):
    # Alternative explicit Postgres env vars (handy on some hosts)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("PGDATABASE") or os.getenv("POSTGRES_DB") or "",
            "USER": os.getenv("PGUSER") or os.getenv("POSTGRES_USER") or "",
            "PASSWORD": os.getenv("PGPASSWORD") or os.getenv("POSTGRES_PASSWORD") or "",
            "HOST": os.getenv("PGHOST") or os.getenv("POSTGRES_HOST") or "localhost",
            "PORT": os.getenv("PGPORT") or os.getenv("POSTGRES_PORT") or "5432",
        }
    }
else:
    # Safe local default
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# DRF / Auth
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Opportunity Finder API",
    "DESCRIPTION": "Backend API for Opportunity Finder (auth, opportunities, matching, notifications).",
    "VERSION": "0.1.0",
    # Swagger UI will use Bearer auth automatically when security schemes are present.
    "SERVE_INCLUDE_SCHEMA": False,
    # Important for file uploads: request schema differs from response schema (URL string vs binary upload).
    "COMPONENT_SPLIT_REQUEST": True,
}

# Telegram ingestion (Pyrogram)
PYROGRAM_API_ID = os.getenv("PYROGRAM_API_ID")
PYROGRAM_API_HASH = os.getenv("PYROGRAM_API_HASH")
PYROGRAM_SESSION_STRING = os.getenv("PYROGRAM_SESSION_STRING")

# Brevo email (transactional)
BREVO_API_KEY = os.getenv("BREVO_API_KEY")
BREVO_SENDER_EMAIL = os.getenv("BREVO_SENDER_EMAIL")
BREVO_SENDER_NAME = os.getenv("BREVO_SENDER_NAME", "Opportunity Finder")

# Frontend URL (for password reset links)
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000").strip().rstrip("/")

# AI (provider router)
AI_PROVIDER = os.getenv("AI_PROVIDER", "stub").strip().lower()
AI_PROVIDER_CHAIN = [p.strip().lower() for p in env_csv("AI_PROVIDER_CHAIN", default=[]) if p.strip()]

# Ingestion
INGESTION_LIMIT_PER_SOURCE = int(os.getenv("INGESTION_LIMIT_PER_SOURCE", "20"))

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")  # Backwards compatibility
GEMINI_API_KEYS = env_csv("GEMINI_API_KEYS", default=None)  # List of keys for rotation
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.0-flash").strip()
GEMINI_API_BASE = os.getenv("GEMINI_API_BASE", "https://generativelanguage.googleapis.com").strip().rstrip("/")
AI_TIMEOUT_SECONDS = float(os.getenv("AI_TIMEOUT_SECONDS", "60"))
AI_TEMPERATURE = float(os.getenv("AI_TEMPERATURE", "0.2"))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# Groq (OpenAI-compatible)
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant").strip()
GROQ_API_BASE = os.getenv("GROQ_API_BASE", "https://api.groq.com/openai/v1").strip().rstrip("/")

# Hugging Face (Inference API)
HF_API_TOKEN = os.getenv("HF_API_TOKEN")  # optional for some models, recommended
HF_MODEL = os.getenv("HF_MODEL", "google/gemma-2b-it").strip()
# Hugging Face deprecated api-inference host; router is the current endpoint.
# Base should be the router host. Endpoints vary by mode below.
HF_API_BASE = os.getenv("HF_API_BASE", "https://router.huggingface.co").strip().rstrip("/")
HF_MODE = os.getenv("HF_MODE", "openai").strip().lower()  # openai | classic
HF_MAX_NEW_TOKENS = int(os.getenv("HF_MAX_NEW_TOKENS", "256"))
HF_WAIT_FOR_MODEL = env_bool("HF_WAIT_FOR_MODEL", default=True)

# Extraction quality control
EXTRACTION_CONFIDENCE_THRESHOLD = float(os.getenv("EXTRACTION_CONFIDENCE_THRESHOLD", "0.6"))

# Celery (async tasks)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE", "UTC")
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_QUEUE_MAX_PRIORITY = 10
CELERY_TASK_QUEUES = (
    Queue("default", queue_arguments={"x-max-priority": CELERY_TASK_QUEUE_MAX_PRIORITY}),
    Queue("priority", queue_arguments={"x-max-priority": CELERY_TASK_QUEUE_MAX_PRIORITY}),
)
CELERY_TASK_ROUTES = {
    "cover_letters.tasks.generate_cover_letter_task": {"queue": "priority"},
    "resume_extractions.tasks.process_cv_extraction": {"queue": "priority"},
}
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Celery Beat (periodic scheduler)
# Runs every minute and enqueues per-Source ingestion tasks if due.
PROCESSING_BEAT_ENABLED = env_bool("PROCESSING_BEAT_ENABLED", default=True)
PROCESSING_BEAT_INTERVAL_SECONDS = float(os.getenv("PROCESSING_BEAT_INTERVAL_SECONDS", "60"))
PROCESSING_PENDING_LIMIT = int(os.getenv("PROCESSING_PENDING_LIMIT", "10"))
# Celery-side throttling for AI calls (helps avoid Gemini/HF rate limits).
# Format examples: "10/m", "1/s", "100/h"
PROCESSING_AI_RATE_LIMIT = os.getenv("PROCESSING_AI_RATE_LIMIT", "3/h").strip()

# Matching (auto-matching for users)
MATCHING_BEAT_ENABLED = env_bool("MATCHING_BEAT_ENABLED", default=False)  # DISABLED to isolate burst source
MATCHING_BEAT_INTERVAL_SECONDS = float(os.getenv("MATCHING_BEAT_INTERVAL_SECONDS", "14400"))  # 4 hours - long intervals to avoid bursts
MATCHING_BATCH_SIZE = int(os.getenv("MATCHING_BATCH_SIZE", "1"))  # Opportunities per batch (reduced to prevent bursts)
# Separate rate limit for matching AI calls (cost control)
MATCHING_AI_RATE_LIMIT = os.getenv("MATCHING_AI_RATE_LIMIT", "1/h").strip()

# Backfill matching (new users)
MATCHING_BACKFILL_DAYS = int(os.getenv("MATCHING_BACKFILL_DAYS", "5"))
MATCHING_BACKFILL_MAX_CANDIDATES = int(os.getenv("MATCHING_BACKFILL_MAX_CANDIDATES", "50"))
MATCHING_BACKFILL_MAX_AI = int(os.getenv("MATCHING_BACKFILL_MAX_AI", "10"))

CELERY_BEAT_SCHEDULE = {
    "ingestion-ingest-due-sources-every-5-minutes": {
        "task": "ingestion.tasks.ingest_due_sources",
        "schedule": 300.0,  # Changed from 60.0 to 300.0 (5 minutes)
        "args": (None, INGESTION_LIMIT_PER_SOURCE),  # source_type=None (all), limit=env
    },
}

if PROCESSING_BEAT_ENABLED:
    CELERY_BEAT_SCHEDULE["processing-process-pending-raw"] = {
        "task": "processing.tasks.process_pending_raw",
        "schedule": PROCESSING_BEAT_INTERVAL_SECONDS,
        "args": (PROCESSING_PENDING_LIMIT,),
    }

if MATCHING_BEAT_ENABLED:
    CELERY_BEAT_SCHEDULE["matching-match-pending-opportunities"] = {
        "task": "matching.tasks.match_pending_opportunities",
        "schedule": MATCHING_BEAT_INTERVAL_SECONDS,
        "args": (24, MATCHING_BATCH_SIZE),  # hours_back=24, batch_size
    }

# Notifications (process pending notifications)
NOTIFICATIONS_BEAT_ENABLED = env_bool("NOTIFICATIONS_BEAT_ENABLED", default=True)
NOTIFICATIONS_BEAT_INTERVAL_SECONDS = float(os.getenv("NOTIFICATIONS_BEAT_INTERVAL_SECONDS", "300"))  # 5 minutes
NOTIFICATIONS_PROCESS_LIMIT = int(os.getenv("NOTIFICATIONS_PROCESS_LIMIT", "50"))  # Per batch

if NOTIFICATIONS_BEAT_ENABLED:
    CELERY_BEAT_SCHEDULE["notifications-process-pending"] = {
        "task": "notifications.tasks.process_pending_notifications",
        "schedule": NOTIFICATIONS_BEAT_INTERVAL_SECONDS,
        "args": (NOTIFICATIONS_PROCESS_LIMIT,),
    }

# Celery task annotations (rate limits, etc.)
CELERY_TASK_ANNOTATIONS = {
    # This is the AI-heavy task; rate-limit it to reduce 429s.
    "processing.tasks.process_raw_opportunity": {"rate_limit": PROCESSING_AI_RATE_LIMIT},
    # Matching tasks (separate rate limit for cost control)
    "matching.tasks.match_opportunity_to_users": {"rate_limit": MATCHING_AI_RATE_LIMIT},
    "matching.tasks.match_single_user_opportunity": {"rate_limit": MATCHING_AI_RATE_LIMIT},
    "matching.tasks.match_pending_opportunities": {"rate_limit": MATCHING_AI_RATE_LIMIT},
    "matching.tasks.backfill_recent_opportunities_for_user": {"rate_limit": MATCHING_AI_RATE_LIMIT},
    # Cover letter generation (higher priority, user-facing)
    "cover_letters.tasks.generate_cover_letter_task": {"rate_limit": "10/m"},  # 10 per minute, higher than matching
    # CV extraction (higher priority, user-facing)
    "resume_extractions.tasks.process_cv_extraction": {"rate_limit": "10/m"},  # 10 per minute, higher than matching
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media (uploads) - used for CV file reference storage in `profiles`
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
# Allow localhost and common network IPs for development
CORS_ALLOWED_ORIGINS = env_csv(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://192.168.146.17:3000",  # Add your network IP
    ]
)

# For development, also allow all origins (less secure, but convenient)
# Set CORS_ALLOW_ALL_ORIGINS=true in .env to enable for mobile testing
# Remove this in production!
if env_bool("CORS_ALLOW_ALL_ORIGINS", default=False):
    CORS_ALLOW_ALL_ORIGINS = True

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allow all headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
