# Generated by Django 6.0 on 2026-01-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("MODERATOR", "Moderator"),
                    ("ADMIN", "Admin"),
                    ("SUPPORT", "Support"),
                ],
                default="USER",
                help_text="User role for access control",
                max_length=20,
            ),
        ),
    ]
