# Generated by Django 6.0 on 2025-12-26 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0008_rawopportunity_content_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(
                        help_text="AI-calculated match score (0-10, higher is better)"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated explanation for the match score",
                    ),
                ),
                (
                    "stage1_passed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this match passed the Stage 1 SQL pre-filter",
                    ),
                ),
                (
                    "stage2_score",
                    models.FloatField(
                        blank=True,
                        help_text="Stage 2 AI re-ranking score (if different from final score)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("NOTIFIED", "Notified"),
                            ("IGNORED", "Ignored"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="matching_ma_user_id_f57f6f_idx"
                    ),
                    models.Index(
                        fields=["opportunity", "match_score"],
                        name="matching_ma_opportu_5a3d82_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="matching_ma_created_9824e1_idx"
                    ),
                    models.Index(
                        fields=["match_score"], name="matching_ma_match_s_e4b125_idx"
                    ),
                ],
                "unique_together": {("user", "opportunity")},
            },
        ),
    ]
