# Generated by Cascade on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_extractions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvextractionsession",
            name="extracted_full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
