# Generated by Django 6.0 on 2025-12-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cover_letters", "0002_add_generating_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="coverletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("GENERATING", "Generating"),
                    ("GENERATED", "Generated"),
                    ("EDITED", "Edited"),
                    ("FINALIZED", "Finalized"),
                    ("FAILED", "Failed"),
                ],
                default="GENERATING",
                max_length=20,
            ),
        ),
    ]
