# Generated by Django 6.0 on 2025-12-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cover_letters", "0003_add_error_message_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
