# Generated by Django 6.0 on 2025-12-16 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "telegram_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("cv_file", models.FileField(blank=True, null=True, upload_to="cvs/")),
                ("cv_text", models.TextField(blank=True, default="")),
                ("academic_info", models.JSONField(blank=True, default=dict)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "matching_doc_version",
                    models.CharField(blank=True, default="v1", max_length=10),
                ),
                ("matching_profile_json", models.JSONField(blank=True, default=dict)),
                ("matching_profile_text", models.TextField(blank=True, default="")),
                (
                    "matching_profile_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
